const fs = require('fs');
// Compact vocab generator for DeutschLern data.js

// Card builder
const cards = [];
const emoji = new Map();

function e(key, val) { if (val && key) emoji.set(key, val); }

// Existing cards from index.html (compact array format)
const EX = [
["a1","noun","n1","der Tisch","table","der","die Tische","table"],
["a1","noun","n2","die Schule","school","die","die Schulen","school"],
["a1","noun","n3","das Buch","book","das","die Bucher","book"],
["a1","noun","n4","der Freund","friend","der","die Freunde","friend"],
["a1","noun","n5","die Familie","family","die","die Familien","family"],
["a1","noun","n6","das Haus","house","das","die Hauser","house"],
["a1","noun","n7","der Mann","man","der","die Manner","man"],
["a1","noun","n8","die Frau","woman","die","die Frauen","woman"],
["a1","noun","n9","das Kind","child","das","die Kinder","child"],
["a1","noun","n10","der Hund","dog","der","die Hunde","dog"],
["a1","noun","n11","der Stuhl","chair","der","die Stuhle","chair"],
["a1","noun","n12","das Bett","bed","das","die Betten","bed"],
["a1","noun","n13","die Kuche","kitchen","die","die Kuchen","kitchen"],
["a1","noun","n14","das Bad","bathroom","das","die Bader","bath"],
["a1","noun","n15","das Brot","bread","das","die Brote","bread"],
["a1","noun","n16","die Milch","milk","die","-","milk"],
["a1","noun","n17","der Kaffee","coffee","der","-","coffee"],
["a1","noun","n18","der Kopf","head","der","die Kopfe","head"],
["a1","noun","n19","die Hand","hand","die","die Hande","hand"],
["a1","noun","n20","das Auge","eye","das","die Augen","eye"],
["a1","noun","n21","der Fuß","foot","der","die Fuße","foot"],
["a1","noun","n22","das Hemd","shirt","das","die Hemden","shirt"],
["a1","noun","n23","die Hose","pants","die","die Hosen","pants"],
["a1","noun","n24","der Schuh","shoe","der","die Schuhe","shoe"],
["a1","noun","n25","die Jacke","jacket","die","die Jacken","jacket"],
["a1","noun","n26","die Farbe","color","die","die Farben","color"],
["a1","noun","n27","die Stadt","city","die","die Stadte","city"],
["a1","noun","n28","der Zug","train","der","die Zuge","train"],
["a1","noun","n29","der Bus","bus","der","die Busse","bus"],
["a1","noun","n30","das Fahrrad","bicycle","das","die Fahrrader","bike"],
["a1","noun","n31","das Wetter","weather","das","-","sun"],
["a1","noun","n32","die Sonne","sun","die","-","sun"],
["a1","noun","n33","der Regen","rain","der","-","rain"],
["a1","verb","v1","sein","to be","1","ist/war/ist gewesen","star"],
["a1","verb","v2","haben","to have","1","hat/hatte/hat gehabt","muscle"],
["a1","verb","v3","werden","to become","1","wird/wurde/ist geworden","cycle"],
["a1","verb","v4","konnen","can/be able to","1","kann/konnte/hat gekonnt","check"],
["a1","verb","v5","mussen","must/have to","1","muss/musste/hat gemusst","warning"],
["a1","verb","v6","sagen","to say","","sagt/sagte/hat gesagt","speech"],
["a1","verb","v7","machen","to do/make","","macht/machte/hat gemacht","tool"],
["a1","verb","v8","gehen","to go","","geht/ging/ist gegangen","walk"],
["a1","verb","v9","kommen","to come","","kommt/kam/ist gekommen","door"],
["a1","verb","v10","sehen","to see","","sieht/sah/hat gesehen","eye"],
["a1","verb","v11","geben","to give","","gibt/gab/hat gegeben","give"],
["a1","verb","v12","essen","to eat","","isst/aß/hat gegessen","eat"],
["a1","verb","v13","trinken","to drink","","trinkt/trank/hat getrunken","drink"],
["a1","verb","v14","sprechen","to speak","","spricht/sprach/hat gesprochen","speak"],
["a1","verb","v15","nehmen","to take","","nimmt/nahm/hat genommen","take"],
["a1","verb","v16","wohnen","to live","","wohnt/wohnte/hat gewohnt","house"],
["a1","verb","v17","kaufen","to buy","","kauft/kaufte/hat gekauft","cart"],
["a1","verb","v18","suchen","to search","","sucht/suchte/hat gesucht","search"],
["a1","verb","v19","finden","to find","","findet/fand/hat gefunden","find"],
["a1","verb","v20","brauchen","to need","","braucht/brauchte/hat gebraucht","need"],
["a1","verb","v21","spielen","to play","","spielt/spielte/hat gespielt","play"],
["a1","adverb","a1","heute","today","","","today"],
["a1","adverb","a2","morgen","tomorrow","","","tomorrow"],
["a1","adverb","a3","gestern","yesterday","","","yesterday"],
["a1","adverb","a4","jetzt","now","","","now"],
["a1","adverb","a5","hier","here","","","here"],
["a1","adverb","a6","da","there","","","there"],
["a1","adverb","a7","sehr","very","","","very"],
["a1","adverb","a8","auch","also/too","","","also"],
["a1","adverb","a9","nicht","not","","","no"],
["a1","adverb","a10","viel","much/many","","","many"],
["a1","phrase","p1","Guten Morgen","Good morning","","","sunrise"],
["a1","phrase","p2","Guten Tag","Good day/Hello","","","sun"],
["a1","phrase","p3","Guten Abend","Good evening","","","sunset"],
["a1","phrase","p4","Gute Nacht","Good night","","","moon"],
["a1","phrase","p5","Tschuss","Bye!","","","wave"],
["a1","phrase","p6","Danke","Thanks","","","pray"],
["a1","phrase","p7","Bitte","Please/You are welcome","","","please"],
["a1","phrase","p8","Prost!","Cheers!","","","cheers"],
["a1","phrase","p9","Entschuldigung","Excuse me/Sorry","","","sorry"],
["a1","phrase","p10","Wie geht es Ihnen?","How are you?","","","hello"],
["a2","noun","n34","die Arbeit","work/job","1","die","die Arbeiten","work"],
["a2","noun","n35","das Buro","office","","das","die Buros","office"],
["a2","noun","n36","der Beruf","profession","","der","die Berufe","tie"],
["a2","noun","n37","der Arzt","doctor","","der","die Arzte","doctor"],
["a2","noun","n38","das Krankenhaus","hospital","","das","die Krankenhauser","hospital"],
["a2","noun","n39","der Schmerz","pain","","der","die Schmerzen","pain"],
["a2","noun","n40","das Restaurant","restaurant","","das","die Restaurants","restaurant"],
["a2","noun","n41","die Rechnung","bill","","die","die Rechnungen","receipt"],
["a2","noun","n42","das Hotel","hotel","","das","die Hotels","hotel"],
["a2","noun","n43","die Reise","trip","","die","die Reisen","travel"],
["a2","noun","n44","die Fahrkarte","ticket","","die","die Fahrkarten","ticket"],
["a2","noun","n45","der Bahnhof","train station","","der","die Bahnhofe","station"],
["a2","noun","n46","der Flughafen","airport","","der","die Flughafen","airport"],
["a2","noun","n47","die Kleidung","clothing","","die","-","clothing"],
["a2","noun","n48","der Preis","price","","der","die Preise","price"],
["a2","noun","n49","das Handy","mobile phone","","das","die Handys","phone"],
["a2","noun","n50","der Geburtstag","birthday","","der","die Geburtstage","birthday"],
["a2","noun","n51","das Geschenk","gift","","das","die Geschenke","gift"],
["a2","noun","n52","die Katze","cat","","die","die Katzen","cat"],
["a2","noun","n53","das Auto","car","","das","die Autos","car"],
["a2","noun","n54","das Wasser","water","","das","-","water"],
["a2","noun","n55","die Blume","flower","","die","die Blumen","flower"],
["a2","noun","n56","der Baum","tree","","der","die Baume","tree"],
["a2","noun","n57","der Schnee","snow","","der","-","snow"],
["a2","verb","v22","arbeiten","to work","1","arbeitet/arbeitete/hat gearbeitet","work"],
["a2","verb","v23","lernen","to learn","1","lernt/lernte/hat gelernt","learn"],
["a2","verb","v24","verstehen","to understand","1","versteht/verstand/hat verstanden","understand"],
["a2","verb","v25","schreiben","to write","1","schreibt/schrieb/hat geschrieben","write"],
["a2","verb","v26","lesen","to read","1","liest/las/hat gelesen","read"],
["a2","verb","v27","fahren","to drive/go","","fahrt/fuhr/ist gefahren","drive"],
["a2","verb","v28","helfen","to help","","hilft/half/hat geholfen","help"],
["a2","verb","v29","bringen","to bring","","bringt/brachte/hat gebracht","bring"],
["a2","verb","v30","denken","to think","1","denkt/dachte/hat gedacht","think"],
["a2","verb","v31","antworten","to answer","","antwortet/antwortete/hat geantwortet","answer"],
["a2","verb","v32","fragen","to ask","","fragt/fragte/hat gefragt","ask"],
["a2","verb","v33","bestellen","to order","","bestellt/bestellte/hat bestellt","order"],
["a2","verb","v34","bezahlen","to pay","","bezahlt/bezahlte/hat bezahlt","pay"],
["a2","verb","v35","kochen","to cook","","kocht/kochte/hat gekocht","cook"],
["a2","verb","v36","wissen","to know","","weiß/wusste/hat gewusst","know"],
["a2","verb","v37","glauben","to believe","","glaubt/glaubte/hat geglaubt","believe"],
["a2","verb","v38","offnen","to open","","offnet/offnete/hat geoffnet","open"],
["a2","verb","v39","schließen","to close","","schließt/schloss/hat geschlossen","close"],
["a2","adverb","a11","immer","always","","","always"],
["a2","adverb","a12","oft","often","","","often"],
["a2","adverb","a13","manchmal","sometimes","","","sometimes"],
["a2","adverb","a14","dort","over there","","","there"],
["a2","adverb","a15","links","left","","","left"],
["a2","adverb","a16","rechts","right","","","right"],
["a2","adverb","a17","geradeaus","straight ahead","","","straight"],
["a2","adverb","a18","vielleicht","maybe","","","maybe"],
["a2","adverb","a19","deshalb","therefore","","","therefore"],
["a2","adverb","a20","zusammen","together","","","together"],
["a2","phrase","p11","Bitte schon","You are welcome","","","smile"],
["a2","phrase","p12","Danke schon","Thank you very much","","","thanks"],
["a2","phrase","p13","Wo ist das?","Where is it?","","","where"],
["a2","phrase","p14","Wie viel kostet das?","How much is that?","","","money"],
["a2","phrase","p15","Ich mochte ...","I would like...","","","want"],
["a2","phrase","p16","Konnen Sie mir helfen?","Can you help me?","","","help"],
["a2","phrase","p17","Es tut mir leid","I am sorry","","","sorry"],
["a2","phrase","p18","Gute Reise!","Have a good trip!","","","travel"],
["a2","phrase","p19","Alles Gute!","All the best!","","","celebration"],
["a2","phrase","p20","Nichts zu danken","Do not mention it","","","smile"],
["b1","noun","n58","die Ausbildung","education/training","1","die","die Ausbildungen","education"],
["b1","noun","n59","das Studium","university studies","1","das","die Studien","study"],
["b1","noun","n60","die Prufung","exam/test","1","die","die Prufungen","exam"],
["b1","noun","n61","der Kurs","course","","der","die Kurse","course"],
["b1","noun","n62","die Note","grade","1","die","die Noten","grade"],
["b1","noun","n63","die Firma","company","","die","die Firmen","company"],
["b1","noun","n64","die Erfahrung","experience","1","die","die Erfahrungen","experience"],
["b1","noun","n65","die Bewerbung","application","","die","die Bewerbungen","application"],
["b1","noun","n66","die Beziehung","relationship","","die","die Beziehungen","relationship"],
["b1","noun","n67","die Umwelt","environment","","die","-","earth"],
["b1","noun","n68","die Energie","energy","","die","die Energien","energy"],
["b1","noun","n69","die Gesellschaft","society","","die","die Gesellschaften","society"],
["b1","noun","n70","die Politik","politics","","die","-","politics"],
["b1","noun","n71","die Kultur","culture","","die","die Kulturen","culture"],
["b1","noun","n72","die Geschichte","history/story","","die","die Geschichten","history"],
["b1","noun","n73","die Bildung","education","","die","-","education"],
["b1","noun","n74","der Computer","computer","","der","die Computer","computer"],
["b1","verb","v40","beginnen","to begin","1","beginnt/begann/hat begonnen","begin"],
["b1","verb","v41","beschreiben","to describe","1","beschreibt/beschrieb/hat beschrieben","describe"],
["b1","verb","v42","erklaren","to explain","1","erklart/erklarte/hat erklart","explain"],
["b1","verb","v43","erwarten","to expect","","erwartet/erwartete/hat erwartet","expect"],
["b1","verb","v44","sich freuen","to be happy about","","freut/freute/hat gefreut","happy"],
["b1","verb","v45","sich interessieren","to be interested","","interessiert/interessierte/hat interessiert","interested"],
["b1","verb","v46","leben","to live","","lebt/lebte/hat gelebt","live"],
["b1","verb","v47","passieren","to happen","","passiert/passierte/ist passiert","happen"],
["b1","verb","v48","reisen","to travel","","reist/reiste/ist gereist","travel"],
["b1","verb","v49","studieren","to study","","studiert/studierte/hat studiert","study"],
["b1","verb","v50","teilnehmen","to participate","1","nimmt teil/nahm teil/hat teilgenommen","participate"],
["b1","verb","v51","verbringen","to spend time","","verbringt/verbrachte/hat verbracht","time"],
["b1","verb","v52","vorschlagen","to suggest","","schlagt vor/schlug vor/hat vorgeschlagen","suggest"],
["b1","verb","v53","sich vorstellen","to introduce","","stellt vor/stellte vor/hat vorgestellt","introduce"],
["b1","verb","v54","gewinnen","to win","","gewinnt/gewann/hat gewonnen","win"],
["b1","verb","v55","wahlen","to choose/elect","","wahlt/wahlte/hat gewahlt","choose"],
["b1","verb","v56","genießen","to enjoy","","genießt/genoss/hat genossen","enjoy"],
["b1","adverb","a21","sofort","immediately","","","immediately"],
["b1","adverb","a22","selten","rarely","","","rarely"],
["b1","adverb","a23","nie","never","","","never"],
["b1","adverb","a24","ziemlich","quite","","","quite"],
["b1","adverb","a25","wirklich","really","","","really"],
["b1","adverb","a26","außerdem","besides/moreover","","","plus"],
["b1","adverb","a27","trotzdem","nevertheless","","","still"],
["b1","adverb","a28","deswegen","therefore","","","therefore"],
["b1","adverb","a29","besonders","especially","","","star"],
["b1","adverb","a30","allerdings","however","","","but"],
["b1","phrase","p21","Ich verstehe nicht","I do not understand","","","confused"],
["b1","phrase","p22","Ich bin mude","I am tired","","","tired"],
["b1","phrase","p23","Das gefallt mir","I like that","","","heart"],
["b1","phrase","p24","Meiner Meinung nach","In my opinion","","","think"],
["b1","phrase","p25","Ich glaube, dass ...","I believe that...","","","believe"],
["b1","phrase","p26","Es kommt darauf an","It depends","","","depends"],
["b1","phrase","p27","Ich habe Lust auf ...","I feel like...","","","want"],
["b1","phrase","p28","Das macht nichts","That does not matter","","","ok"],
["b1","phrase","p29","Ich bin einverstanden","I agree","","","agree"],
["b1","phrase","p30","Keine Ahnung","No idea","","","shrug"],
["b2","noun","n75","die Wirtschaft","economy","","die","-","economy"],
["b2","noun","n76","das Unternehmen","company","","das","die Unternehmen","company"],
["b2","noun","n77","die Entwicklung","development","","die","die Entwicklungen","growth"],
["b2","noun","n78","die Forschung","research","","die","die Forschungen","research"],
["b2","noun","n79","die Wissenschaft","science","","die","die Wissenschaften","science"],
["b2","noun","n80","das Recht","right/law","","das","die Rechte","law"],
["b2","noun","n81","das Gesetz","law","","das","die Gesetze","law"],
["b2","noun","n82","die Freiheit","freedom","","die","-","freedom"],
["b2","noun","n83","die Zukunft","future","","die","-","future"],
["b2","noun","n84","die Entscheidung","decision","1","die","die Entscheidungen","decision"],
["b2","noun","n85","die Veranderung","change","","die","die Veranderungen","change"],
["b2","noun","n86","die Moglichkeit","possibility","1","die","die Moglichkeiten","possibility"],
["b2","noun","n87","der Vertrag","contract","","der","die Vertrage","contract"],
["b2","noun","n88","die Steuer","tax","","die","die Steuern","tax"],
["b2","noun","n89","der Markt","market","","der","die Markte","market"],
["b2","noun","n90","die Krise","crisis","","die","die Krisen","crisis"],
["b2","noun","n91","die Gerechtigkeit","justice","","die","-","justice"],
["b2","noun","n92","die Verantwortung","responsibility","1","die","-","responsibility"],
["b2","noun","n93","die Wahrheit","truth","","die","-","truth"],
["b2","verb","v57","beeinflussen","to influence","","beeinflusst/beeinflusste/hat beeinflusst","influence"],
["b2","verb","v58","vermeiden","to avoid","","vermeidet/vermied/hat vermieden","avoid"],
["b2","verb","v59","entwickeln","to develop","","entwickelt/entwickelte/hat entwickelt","develop"],
["b2","verb","v60","unterstutzen","to support","","unterstutzt/unterstutzte/hat unterstutzt","support"],
["b2","verb","v61","analysieren","to analyze","","analysiert/analysierte/hat analysiert","analyze"],
["b2","verb","v62","beweisen","to prove","","beweist/bewies/hat bewiesen","prove"],
["b2","verb","v63","diskutieren","to discuss","1","diskutiert/diskutierte/hat diskutiert","discuss"],
["b2","verb","v64","sich entscheiden","to decide","1","entscheidet/entschied/hat entschieden","decide"],
["b2","verb","v65","ermoglichen","to enable","","ermoglicht/ermoglichte/hat ermoglicht","enable"],
["b2","verb","v66","grunden","to found","","grundet/grundete/hat gegrundet","found"],
["b2","verb","v67","vergleichen","to compare","1","vergleicht/verglich/hat verglichen","compare"],
["b2","verb","v68","verursachen","to cause","","verursacht/verursachte/hat verursacht","cause"],
["b2","verb","v69","erhohen","to increase","","erhoht/erhohste/hat erhoht","increase"],
["b2","verb","v70","leisten","to achieve","","leistet/leistete/hat geleistet","achieve"],
["b2","adverb","a31","fast","almost","","","almost"],
["b2","adverb","a32","uberall","everywhere","","","everywhere"],
["b2","adverb","a33","moglicherweise","possibly","","","maybe"],
["b2","adverb","a34","durchaus","absolutely","","","check"],
["b2","adverb","a35","inzwischen","meanwhile","","","meanwhile"],
["b2","adverb","a36","dennoch","nevertheless","","","still"],
["b2","adverb","a37","folglich","consequently","","","consequence"],
["b2","adverb","a38","keinesfalls","by no means","","","no"],
["b2","adverb","a39","beinahe","nearly","","","almost"],
["b2","adverb","a40","nirgends","nowhere","","","nowhere"],
["b2","phrase","p31","Es handelt sich um ...","It is about...","","","about"],
["b2","phrase","p32","Ich freue mich darauf","I look forward to it","","","excited"],
["b2","phrase","p33","Das ist mir egal","I do not care","","","careless"],
["b2","phrase","p34","Aus meiner Sicht","From my perspective","","","view"],
["b2","phrase","p35","Ich bin der Meinung, dass","I am of the opinion that","","","opinion"],
["b2","phrase","p36","Es besteht die Moglichkeit","There is the possibility","","","possible"],
["b2","phrase","p37","Es kommt darauf an, ob","It depends whether","","","depends"],
["b2","phrase","p38","Im Großen und Ganzen","By and large","","","overall"],
["a1","question","q1","Wer?","Who?","1","","who"],
["a1","question","q2","Was?","What?","1","","what"],
["a1","question","q3","Wo?","Where?","1","","where"],
["a1","question","q4","Wohin?","Where to?","1","","whereto"],
["a1","question","q5","Woher?","Where from?","1","","wherefrom"],
["a1","question","q6","Wie?","How?","1","","how"],
["a2","question","q7","Wann?","When?","1","","when"],
["a2","question","q8","Warum?","Why?","1","","why"],
["b1","question","q9","Welcher / Welche / Welches?","Which?","1","","which"],
["a1","question","q10","Ja/Nein Frage","Yes/No question (verb first)","1","","yesno"],
["a1","case","c1","Nominativ","Subject case (who/what)","1","","subject"],
["a1","case","c2","Akkusativ","Direct object (whom/what)","1","","target"],
["a2","case","c3","Dativ","Indirect object (to whom)","1","","gift"],
["b1","case","c4","Genitiv","Possession (whose)","1","","possession"],
["a1","grammar","g1","Satzbau","Verb is 2nd position in main clause","1","","structure"],
["a2","grammar","g2","Nebensatz","Sub clause: verb goes to the end","1","","chain"],
["a1","grammar","g3","Prasens","Present tense","1","","present"],
["a2","grammar","g4","Perfekt","Perfect tense: haben/sein + Partizip II","1","","past"],
["b1","grammar","g5","Trennbare Verben","Separable prefix verbs","1","","split"],
["a1","grammar","g6","Modalverben","Modal verbs + infinitive at end","1","","modal"],
["b1","grammar","g7","Adjektivendungen","Adjective endings after article","1","","paint"],
["b1","grammar","g8","Komparativ","Comparative: schneller, besser","1","","graph"],
["a2","grammar","g9","Praspositionen","Two-way prepositions: in, auf, unter...","1","","compass"],
["b2","grammar","g10","Passiv","Passive: werden + Partizip II","1","","passive"],
["b2","grammar","g11","Konjunktiv II","Would/could: wurde + Infinitiv","1","","subjunctive"],
["a2","grammar","g12","Reflexive Verben","Verb + sich: ich wasche mich","1","","reflexive"],
];

// Parse existing
function pe(arr) {
  const [level, type, id, german, english, exam, extra, emoji] = arr;
  const c = {id,level,type,german,english,emoji};
  if (exam === '1') c.exam = true;
  if (type === 'noun') { c.article = extra; c.plural = arr[7]; c.emoji = arr[8] || emoji; }
  else if (type === 'verb') { c.pattern = extra; c.emoji = arr[7] || emoji; }
  return c;
}

for (const e of EX) { 
  cards.push(pe(e));
  const em = pe(e).emoji;
  e('placeholder', '✨');
}

console.log('Existing cards:', cards.length);

// Generate output
const totalCards = cards.reduce((acc, c) => acc + 1, 0);
console.log(`Total: ${totalCards} cards`);
